// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to record a consultation with the AI Symptom Assistant in the user's health record.
 *
 * - recordConsultation - A function that handles the recording of the consultation.
 * - RecordConsultationInput - The input type for the recordConsultation function.
 * - RecordConsultationOutput - The return type for the recordConsultation function.
 */

import { generateJson } from '@/ai/groq';
import { z } from 'zod';

const RecordConsultationInputSchema = z.object({
  symptoms: z.string().describe("Les symptômes décrits par l'utilisateur."),
  differentialDiagnosis: z.string().describe("Le diagnostic différentiel suggéré par l'IA."),
  remedyRecommendations: z.string().describe("Les conseils pratiques et les recommandations fournis."),
});
export type RecordConsultationInput = z.infer<typeof RecordConsultationInputSchema>;

const RecordConsultationOutputSchema = z.object({
  recordId: z.string().describe("L'ID de l'entrée du dossier de santé."),
  summary: z.string().describe("Un résumé concis de la consultation, mettant en évidence les termes importants avec des balises ** (par exemple, **migraine**)."),
});
export type RecordConsultationOutput = z.infer<typeof RecordConsultationOutputSchema>;

export async function recordConsultation(input: RecordConsultationInput): Promise<RecordConsultationOutput> {
  const system = 'Vous êtes un assistant de dossier de santé IA. Vous retournez un JSON minimal.';
  const user = `Rédigez un résumé concis et lisible de cette consultation, en français, avec mise en évidence **bold** pour les termes importants.\n\nSymptômes: ${input.symptoms}\nDiagnostic différentiel: ${input.differentialDiagnosis}\nRecommandations: ${input.remedyRecommendations}`;

  try {
    const { summary } = await generateJson<{ summary: string }>({
      system,
      user,
      schemaName: 'RecordConsultationSummary',
      schema: { type: 'object', properties: { summary: { type: 'string' } }, required: ['summary'] },
      temperature: 0.2,
      maxTokens: 300,
    });

    const recordId = (globalThis.crypto?.randomUUID?.() ?? `rec_${Date.now()}`);
    return { recordId, summary };
  } catch (e) {
    console.error('Groq recordConsultation failed', e);
    const recordId = (globalThis.crypto?.randomUUID?.() ?? `rec_${Date.now()}`);
    return { recordId, summary: "Résumé indisponible pour le moment." };
  }
}
