// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to record a consultation with the AI Symptom Assistant in the user's health record.
 *
 * - recordConsultation - A function that handles the recording of the consultation.
 * - RecordConsultationInput - The input type for the recordConsultation function.
 * - RecordConsultationOutput - The return type for the recordConsultation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecordConsultationInputSchema = z.object({
  symptoms: z.string().describe('The symptoms described by the user.'),
  differentialDiagnosis: z.string().describe('The differential diagnosis suggested by the AI.'),
  remedyRecommendations: z.string().describe('The practical advice and recommendations provided.'),
});
export type RecordConsultationInput = z.infer<typeof RecordConsultationInputSchema>;

const RecordConsultationOutputSchema = z.object({
  recordId: z.string().describe('The ID of the health record entry.'),
  summary: z.string().describe('A summary of the consultation recorded in the health record.'),
});
export type RecordConsultationOutput = z.infer<typeof RecordConsultationOutputSchema>;

export async function recordConsultation(input: RecordConsultationInput): Promise<RecordConsultationOutput> {
  return recordConsultationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recordConsultationPrompt',
  input: {schema: RecordConsultationInputSchema},
  output: {schema: RecordConsultationOutputSchema},
  prompt: `You are an AI health record assistant. Your task is to record the details of a consultation with the AI Symptom Assistant in the user's health record.

  Symptoms: {{{symptoms}}}
  Differential Diagnosis: {{{differentialDiagnosis}}}
  Remedy Recommendations: {{{remedyRecommendations}}}

  Generate a summary of the consultation and return a record ID for the health record entry.
`,
});

const recordConsultationFlow = ai.defineFlow(
  {
    name: 'recordConsultationFlow',
    inputSchema: RecordConsultationInputSchema,
    outputSchema: RecordConsultationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
