// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to record a consultation with the AI Symptom Assistant in the user's health record.
 *
 * - recordConsultation - A function that handles the recording of the consultation.
 * - RecordConsultationInput - The input type for the recordConsultation function.
 * - RecordConsultationOutput - The return type for the recordConsultation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecordConsultationInputSchema = z.object({
  symptoms: z.string().describe("Les symptômes décrits par l'utilisateur."),
  differentialDiagnosis: z.string().describe("Le diagnostic différentiel suggéré par l'IA."),
  remedyRecommendations: z.string().describe("Les conseils pratiques et les recommandations fournis."),
});
export type RecordConsultationInput = z.infer<typeof RecordConsultationInputSchema>;

const RecordConsultationOutputSchema = z.object({
  recordId: z.string().describe("L'ID de l'entrée du dossier de santé."),
  summary: z.string().describe("Un résumé concis de la consultation, mettant en évidence les termes importants avec des balises ** (par exemple, **migraine**)."),
});
export type RecordConsultationOutput = z.infer<typeof RecordConsultationOutputSchema>;

export async function recordConsultation(input: RecordConsultationInput): Promise<RecordConsultationOutput> {
  return recordConsultationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recordConsultationPrompt',
  input: {schema: RecordConsultationInputSchema},
  output: {schema: RecordConsultationOutputSchema},
  prompt: `Vous êtes un assistant de dossier de santé IA. Votre tâche est de créer un résumé très concis et facile à lire d'une consultation, en français.

  Informations de la consultation :
  - Symptômes : {{{symptoms}}}
  - Diagnostic Différentiel : {{{differentialDiagnosis}}}
  - Recommandations : {{{remedyRecommendations}}}

  Instructions :
  1. Générez un résumé qui va droit au but. Par exemple : "Pour des symptômes de **fièvre** et **toux**, un diagnostic possible de **grippe** a été suggéré."
  2. Mettez en évidence les termes médicaux et les diagnostics les plus importants en les entourant de **deux astérisques**. Par exemple : **migraine**, **ibuprofène**.
  3. Retournez un ID de dossier unique pour cette entrée.
`,
});

const recordConsultationFlow = ai.defineFlow(
  {
    name: 'recordConsultationFlow',
    inputSchema: RecordConsultationInputSchema,
    outputSchema: RecordConsultationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
