// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to translate text to a specified language.
 *
 * - translateText - A function that handles text translation.
 * - TranslateTextInput - The input type for the translateText function.
 * - TranslateTextOutput - The return type for the translateText function.
 */

import { generateJson } from '@/ai/groq';
import { z } from 'zod';

const TranslateTextInputSchema = z.object({
  textToTranslate: z.string().describe('The text to be translated.'),
  targetLanguage: z.string().describe('The target language for translation (e.g., "Tunisian Arabic", "English").'),
});
export type TranslateTextInput = z.infer<typeof TranslateTextInputSchema>;

const TranslateTextOutputSchema = z.object({
  translatedText: z.string().describe('The translated text.'),
});
export type TranslateTextOutput = z.infer<typeof TranslateTextOutputSchema>;

export async function translateText(input: TranslateTextInput): Promise<TranslateTextOutput> {
  const system = 'You are a helpful translator.';
  const user = `Translate the following text into ${input.targetLanguage}. Return a JSON with a single property translatedText.\n\nText:\n${input.textToTranslate}`;

  try {
    const { translatedText } = await generateJson<{ translatedText: string}>({
      system,
      user,
      schemaName: 'TranslateTextOutput',
      schema: { type: 'object', properties: { translatedText: { type: 'string' } }, required: ['translatedText'] },
      temperature: 0.0,
      maxTokens: 400,
      jsonStrict: true,
    });
    return { translatedText };
  } catch (e) {
    console.error('Groq translateText failed', e);
    return { translatedText: input.textToTranslate };
  }
}
