// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to translate text to a specified language.
 *
 * - translateText - A function that handles text translation.
 * - TranslateTextInput - The input type for the translateText function.
 * - TranslateTextOutput - The return type for the translateText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TranslateTextInputSchema = z.object({
  textToTranslate: z.string().describe('The text to be translated.'),
  targetLanguage: z.string().describe('The target language for translation (e.g., "Tunisian Arabic", "English").'),
});
export type TranslateTextInput = z.infer<typeof TranslateTextInputSchema>;

const TranslateTextOutputSchema = z.object({
  translatedText: z.string().describe('The translated text.'),
});
export type TranslateTextOutput = z.infer<typeof TranslateTextOutputSchema>;

export async function translateText(input: TranslateTextInput): Promise<TranslateTextOutput> {
  try {
    console.log('Début de la traduction avec l\'entrée :', input);
    const result = await translateTextFlow(input);
    console.log('Traduction réussie :', result);
    return result;
  } catch (error) {
    console.error('Erreur lors de la traduction :', error);
    
    let errorMessage = "Une erreur est survenue lors de la traduction. Veuillez réessayer.";
    
    if (error instanceof Error) {
      console.error('Détails de l\'erreur de traduction:', {
        name: error.name,
        message: error.message,
        stack: error.stack
      });
      
      if (error.message.includes('401') || error.message.includes('unauthorized')) {
        errorMessage = "Erreur d'authentification avec l'API. Veuillez vérifier votre configuration.";
      } else if (error.message.includes('429') || error.message.includes('rate limit')) {
        errorMessage = "Trop de requêtes. Veuillez réessayer dans quelques instants.";
      } else if (error.message.includes('timeout')) {
        errorMessage = "Le serveur met trop temps à répondre. Veuillez réessayer.";
      }
    }
    
    return {
      translatedText: errorMessage
    };
  }
}

const prompt = ai.definePrompt({
  name: 'translateTextPrompt',
  model: 'groq/llama-3.3-70b-versatile',
  input: {schema: TranslateTextInputSchema},
  output: {schema: TranslateTextOutputSchema},
  config: {
    temperature: 0.3,
    maxOutputTokens: 1024,
  },
  prompt: `Translate the following text into {{targetLanguage}}. Return only the translated text.

Text to translate:
"{{textToTranslate}}"
`,
});

const translateTextFlow = ai.defineFlow(
  {
    name: 'translateTextFlow',
    inputSchema: TranslateTextInputSchema,
    outputSchema: TranslateTextOutputSchema,
  },
  async input => {
    try {
      console.log('Début du flux de traduction avec l\'entrée :', input);
      const {output} = await prompt(input);
      console.log('Flux de traduction terminé avec le résultat :', output);
      return output!;
    } catch (error) {
      console.error('Erreur dans translateTextFlow:', error);
      
      let errorMessage = "Une erreur est survenue lors du traitement de votre demande. Veuillez réessayer.";
      
      if (error instanceof Error) {
        console.error('Détails de l\'erreur:', {
          name: error.name,
          message: error.message,
          stack: error.stack
        });
        
        if (error.message.includes('401') || error.message.includes('unauthorized')) {
          errorMessage = "Erreur d'authentification avec l'API Groq. Veuillez vérifier votre configuration.";
        } else if (error.message.includes('429') || error.message.includes('rate limit')) {
          errorMessage = "Trop de requêtes. Veuillez réessayer dans quelques instants.";
        } else if (error.message.includes('timeout')) {
          errorMessage = "Le serveur met trop temps à répondre. Veuillez réessayer.";
        } else if (error.message.includes('network') || error.message.includes('fetch')) {
          errorMessage = "Erreur de connexion à l'API Groq. Veuillez vérifier votre connexion.";
        }
      }
      
      return {
        translatedText: errorMessage
      };
    }
  }
);
