/**
 * @fileoverview This file contains mock data for doctors and specialties.
 */

export type Doctor = {
  id: string;
  name: string;
  specialty: string;
  phone: string;
  address: string;
  city: string;
  hours: string;
  location: {
    lat: number;
    lng: number;
  };
};

export const specialties = [
  "Généraliste",
  "Pédiatre",
  "Gynécologue",
  "Cardiologue",
  "ORL",
  "Dentiste",
  "Dermatologue",
  "Ophtalmologue",
  "Neurologue",
  "Urologue",
  "Rhumatologue",
  "Psychiatre",
];

export const doctors: Doctor[] = [
  {
    id: "doc1",
    name: "Dr. Ahmed Ben Ali",
    specialty: "Généraliste",
    phone: "+216 71 123 456",
    address: "123 Rue de la Liberté, Tunis",
    city: "Tunis",
    hours: "Lundi - Vendredi, 9:00 - 17:00",
    location: { lat: 36.809, lng: 10.18 },
  },
  {
    id: "doc2",
    name: "Dr. Fatma Sassi",
    specialty: "Pédiatre",
    phone: "+216 71 234 567",
    address: "45 Avenue Habib Bourguiba, Tunis",
    city: "Tunis",
    hours: "Mardi, Jeudi, 9:00 - 18:00",
    location: { lat: 36.800, lng: 10.185 },
  },
  {
    id: "doc3",
    name: "Dr. Youssef Trabelsi",
    specialty: "Cardiologue",
    phone: "+216 71 345 678",
    address: "Clinique El Manar, Tunis",
    city: "Tunis",
    hours: "Lundi - Samedi, 8:00 - 16:00",
    location: { lat: 36.83, lng: 10.15 },
  },
  {
    id: "doc4",
    name: "Dr. Amira Bouaziz",
    specialty: "Gynécologue",
    phone: "+216 73 456 789",
    address: "10 Rue de l'Indépendance, Sousse",
    city: "Sousse",
    hours: "Lundi, Mercredi, Vendredi, 10:00 - 19:00",
    location: { lat: 35.825, lng: 10.641 },
  },
  {
    id: "doc5",
    name: "Dr. Karim Zied",
    specialty: "ORL",
    phone: "+216 71 567 890",
    address: "22 Rue de Carthage, Tunis",
    city: "Tunis",
    hours: "Mardi - Samedi, 9:00 - 17:00",
    location: { lat: 36.79, lng: 10.18 },
  },
    {
    id: "doc6",
    name: "Dr. Sana Khemiri",
    specialty: "Dentiste",
    phone: "+216 72 678 901",
    address: "55 Rue des Palmiers, Nabeul",
    city: "Nabeul",
    hours: "Lundi - Vendredi, 8:30 - 17:30",
    location: { lat: 36.456, lng: 10.735 },
  },
  {
    id: "doc7",
    name: "Dr. Mehdi Chebbi",
    specialty: "Dermatologue",
    phone: "+216 71 789 012",
    address: "8 Rue de la Marsa, La Marsa",
    city: "La Marsa",
    hours: "Lundi, Mercredi, 14:00 - 20:00",
    location: { lat: 36.877, lng: 10.325 },
  },
  {
    id: "doc8",
    name: "Dr. Nadia Gharbi",
    specialty: "Généraliste",
    phone: "+216 71 890 123",
    address: "33 Avenue Charles de Gaulle, Tunis",
    city: "Tunis",
    hours: "Lundi - Samedi, 8:00 - 13:00",
    location: { lat: 36.805, lng: 10.182 },
  },
  {
    id: "doc9",
    name: "Dr. Hichem Fkih",
    specialty: "Ophtalmologue",
    phone: "+216 74 123 123",
    address: "Avenue du 14 Janvier, Sfax",
    city: "Sfax",
    hours: "Lundi - Vendredi, 9:00 - 16:30",
    location: { lat: 34.74, lng: 10.76 },
  },
  {
    id: "doc10",
    name: "Dr. Selma Gueddes",
    specialty: "Neurologue",
    phone: "+216 72 234 234",
    address: "Rue de l'Hôpital, Bizerte",
    city: "Bizerte",
    hours: "Mardi, Jeudi, 10:00 - 17:00",
    location: { lat: 37.274, lng: 9.873 },
  },
  {
    id: "doc11",
    name: "Dr. Anis Ltaief",
    specialty: "Urologue",
    phone: "+216 73 345 345",
    address: "Boulevard de l'Environnement, Sousse",
    city: "Sousse",
    hours: "Mercredi, Vendredi, 8:30 - 15:00",
    location: { lat: 35.83, lng: 10.61 },
  },
  {
    id: "doc12",
    name: "Dr. Rym Bali",
    specialty: "Rhumatologue",
    phone: "+216 71 456 456",
    address: "Rue du Lac Leman, Les Berges du Lac, Tunis",
    city: "Tunis",
    hours: "Lundi - Jeudi, 15:00 - 19:00",
    location: { lat: 36.844, lng: 10.28 },
  },
  {
    id: "doc13",
    name: "Dr. Walid Mhadhbi",
    specialty: "Psychiatre",
    phone: "+216 75 567 567",
    address: "Avenue des Martyrs, Gabès",
    city: "Gabès",
    hours: "Sur rendez-vous",
    location: { lat: 33.881, lng: 10.098 },
  },
  {
    id: "doc14",
    name: "Dr. Leila Ben Miled",
    specialty: "Pédiatre",
    phone: "+216 73 678 678",
    address: "Rue Ibn Khaldoun, Monastir",
    city: "Monastir",
    hours: "Lundi - Samedi, 9:00 - 14:00",
    location: { lat: 35.766, lng: 10.82 },
  },
  {
    id: "doc15",
    name: "Dr. Sofiene Chaari",
    specialty: "Cardiologue",
    phone: "+216 74 789 789",
    address: "Route de Teniour, Sfax",
    city: "Sfax",
    hours: "Lundi - Vendredi, 8:00 - 17:00",
    location: { lat: 34.76, lng: 10.74 },
  },
  {
    id: "doc16",
    name: "Dr. Meriem Masmoudi",
    specialty: "Gynécologue",
    phone: "+216 74 890 890",
    address: "Avenue Majida Boulila, Sfax",
    city: "Sfax",
    hours: "Lundi - Samedi, 10:00 - 18:00",
    location: { lat: 34.735, lng: 10.755 },
  },
  {
    id: "doc17",
    name: "Dr. Khaled Ben Rhouma",
    specialty: "Généraliste",
    phone: "+216 72 901 901",
    address: "Avenue de la République, Hammamet",
    city: "Hammamet",
    hours: "Lundi - Vendredi, 9:00 - 12:00, 15:00 - 19:00",
    location: { lat: 36.4, lng: 10.616 },
  },
  {
    id: "doc18",
    name: "Dr. Asma Laribi",
    specialty: "Dentiste",
    phone: "+216 71 012 012",
    address: "Centre Urbain Nord, Tunis",
    city: "Tunis",
    hours: "Mardi - Samedi, 10:00 - 19:00",
    location: { lat: 36.85, lng: 10.2 },
  },
  {
    id: "doc19",
    name: "Dr. Fares Belhaj",
    specialty: "ORL",
    phone: "+216 72 123 212",
    address: "7 Rue d'Espagne, Bizerte",
    city: "Bizerte",
    hours: "Lundi, Mercredi, Vendredi, 8:00 - 14:00",
    location: { lat: 37.27, lng: 9.87 },
  },
  {
    id: "doc20",
    name: "Dr. Cyrine Chaabane",
    specialty: "Dermatologue",
    phone: "+216 73 234 323",
    address: "Corniche, Sousse",
    city: "Sousse",
    hours: "Sur rendez-vous",
    location: { lat: 35.83, lng: 10.635 },
  },
  {
    id: "doc21",
    name: "Dr. Samy Hamdi",
    specialty: "Généraliste",
    phone: "+216 75 345 434",
    address: "Rue Taieb Mhiri, Houmt Souk, Djerba",
    city: "Djerba",
    hours: "Lundi - Samedi, 8:30 - 16:30",
    location: { lat: 33.875, lng: 10.858 },
  },
  {
    id: "doc22",
    name: "Dr. Ines Abid",
    specialty: "Ophtalmologue",
    phone: "+216 71 456 545",
    address: "Clinique La Soukra, L'Aouina",
    city: "L'Aouina",
    hours: "Mardi, Jeudi, 9:00 - 17:00",
    location: { lat: 36.86, lng: 10.26 },
  },
  {
    id: "doc23",
    name: "Dr. Mourad Slim",
    specialty: "Cardiologue",
    phone: "+216 71 567 656",
    address: "Rue de la Clinique, El Mourouj",
    city: "El Mourouj",
    hours: "Lundi - Vendredi, 9:00 - 16:00",
    location: { lat: 36.71, lng: 10.18 },
  }
];

export const cities = [...new Set(doctors.map(doc => doc.city))];
